### ISSUE TITLE
Consider including a couple of other iterators

### ISSUE THREAD

**Issue by dave1010** [hoaproject/Iterator#18]
I wrote a couple of standalone iterators. One for caching non-rewindable iterators (so they can be rewound) and 1 for yielding a combination of values from multiple iterators in a kind of round-robin style.

Currently MIT license but can be changed.

https://github.com/wearebase/base-core/tree/master/src/Iterator
https://github.com/wearebase/base-core/tree/master/tests/Iterator

They're used in production in a couple of places and are fairly well tested. May need a few tweaks in naming / style to get into Hoa.

**Comment by Hywan** [comment]
Ping?
